### ISSUE TITLE
Update packages due to security vulnerabilities

### ISSUE THREAD

**Issue by nunofgs** [uphold/koa-error-mapper#32]
We need someone to update each package currently flagged with vulnerabilities (handlebars, lodash, eslint). Please also take care that no breaking changes occur due to the upgrade.

**Comment by bamoha** [comment]
Hii.. I am on this

**Comment by bamoha** [comment]
Lodash and handlebars are not dependencies on this project

**Comment by vladanpaunovic** [comment]
Done! :)
